version: 2

models:
  - name: stg_ga4_events
    description: "Raw GA4 data extracted and cleaned from the BigQuery public dataset."
    columns:
      - name: event_timestamp
        tests:
          - not_null
      - name: user_pseudo_id
        tests:
          - not_null
  
  - name: int_sessions
    description: "Sessionized user events with first and last touch attribution fields."
    columns: 
      - name: user_key
        tests: 
          - not_null
  
  - name: mart_attribution_first
    description: "First click attribution segregated by day, source, and medium."
    columns: 
      - name: session_date
        tests: 
          - not_null

  - name: mart_attribution_last
    description: "Last click attribution segregated by day, source, and medium."
    columns:
      - name: session_date
        tests: 
          - not_null
      